# Generated by Django 4.2.7 on 2026-02-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_doctor_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meet_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
