# Generated by Django 4.2.7 on 2026-03-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_appointment_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='reminder_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
