# Generated by Django 4.2.7 on 2026-03-29 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_medicalreport_reminder_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('exercise', 'exercise'), ('diet', 'diet'), ('medicine', 'medicine'), ('general', 'general')], default='general', max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(blank=True, default='')),
                ('scheduled_for', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.medicalreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'scheduled_for'], name='website_ina_user_id_f1a597_idx'), models.Index(fields=['user', 'delivered_at'], name='website_ina_user_id_6175d7_idx')],
            },
        ),
    ]
