# Generated by Django 4.2.7 on 2026-03-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inappnotification',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['user', 'taken_at'], name='website_ina_user_id_a03ea6_idx'),
        ),
    ]
